export interface IEmployees {
    id: number,
    name: string,
    lastName: string,
    pfp: string,
    email: string,
    username: string,
    age: number,
    staff: string,
    company: string,
    address: string,
    phone: number,
    city: string,
    country: string,
    userInformation: string,
    postalCode: number,
    aboutMe: string,
    id_admin: number,
}