export interface IEmployees {
    id: number,
    name: number,
    lastName: number,
    email: number,
    password: number,
    username: number,
    age: number,
    staff: number,
    company: number,
    address: number,
    phone: number,
    city: number,
    country: number,
    userInformation: number,
    postalCode: number,
    aboutMe: number,
    positionemployee: number,
    id_user: number,
}